eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: suretime-service
        uri: lb://SURETIME-SERVICE
        predicates:
        - Path=/person/**
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**

server:
  port: 8989